:plugins:
  :ha_proxy:
    :disabled: :auto
    :interval: 5
    :backends: true
    :frontends: false
    :servers: false
    :attributes: [qcur, qmax, scur, smax, bin, bout, econ, eresp]
    :socket_file: /var/run/haproxy.sock
  :passenger:
    :disabled: :auto
    :interval: 5
:reporting_rate: 10

	