:plugins:
  :ha_proxy:
    :disabled: :retry
    :interval: 5
    :backends: true
    :frontends: false
    :servers: false
    :attributes: [qcur, qmax, scur, smax, bin, bout, econ, eresp, act]
    :socket_file: /var/run/haproxy.sock
  :passenger:
    :disabled: :retry
    :interval: 5
  :snippet_cache:
    :disabled: :retry
    :interval: 5
    :require: /usr/local/lib/snippet_cache/snippet_cache.rb
:reporting_rate: 120

  